import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import type { TypegenKind, TypegenState } from "./state.js";

// An empty build collection types as `never`; an empty live collection or pack falls back to `string`, since it may just mean the source couldn't list its icons.
const KIND_CONFIG = {
  build: { interfaceName: "Collections", emptyValueType: "never" },
  live: { interfaceName: "LiveCollections", emptyValueType: "string" },
  packs: { interfaceName: "Packs", emptyValueType: "string" },
} as const satisfies Record<TypegenKind, { interfaceName: string; emptyValueType: string }>;

export function partialFilename(kind: TypegenKind, collection: string): string {
  // Sanitized since collection names are arbitrary user-chosen identifiers; prefixed by kind to avoid a name collision across kinds.
  const safeName = collection.replace(/[^a-zA-Z0-9_-]/g, "_");
  return `${kind}-${safeName}.d.ts`;
}

function namesHash(names: string[]): string {
  return createHash("sha256")
    .update([...names].sort().join(","))
    .digest("hex");
}

async function tryGetHash(path: URL): Promise<string | undefined> {
  try {
    const text = await readFile(path, { encoding: "utf-8" });
    return text.split("\n", 2)[1]?.replace("// ", "");
  } catch {}
}

function unionOf(names: string[]): string {
  return names.map((icon) => `"${icon}"`).join(" | ");
}

function renderPartial(
  kind: TypegenKind,
  collection: string,
  names: string[],
  hash: string,
): string {
  const key = JSON.stringify(collection);
  const { interfaceName, emptyValueType } = KIND_CONFIG[kind];
  const valueType = names.length > 0 ? unionOf(names) : emptyValueType;
  const body = `interface ${interfaceName} {\n\t\t${key}: ${valueType};\n\t}`;

  return `// Automatically generated by astro-icon
// ${hash}

declare namespace AstroIcon {
\t${body}
}
`;
}

/** Rewrites one kind/collection's partial declaration file, skipping the write if its icon name set hasn't changed. */
export async function writePartial(
  partialsDir: URL,
  kind: TypegenKind,
  collection: string,
  names: string[],
): Promise<void> {
  const partialFile = new URL(`./${partialFilename(kind, collection)}`, partialsDir);
  const currentHash = namesHash(names);
  const oldHash = await tryGetHash(partialFile);
  if (currentHash === oldHash) return;

  await writeFile(partialFile, renderPartial(kind, collection, names, currentHash));
}

/** Renders the aggregating index that references every kind/collection's own partial. */
export function renderIndex(state: TypegenState): string {
  const references = [
    ...Object.keys(state.build).map((name) => partialFilename("build", name)),
    ...Object.keys(state.live).map((name) => partialFilename("live", name)),
    ...Object.keys(state.packs).map((name) => partialFilename("packs", name)),
  ]
    .sort()
    .map((file) => `/// <reference path="./astro-icon/${file}" />`)
    .join("\n");

  return `// Automatically generated by astro-icon - references one declaration file
// per collection under ./astro-icon/, each merging into the AstroIcon
// namespace used by IconName/LiveCollectionName.
${references}
`;
}
