packages:
  - "packages/*"
  - "demo"

allowBuilds:
  esbuild: true

overrides:
  picomatch@<2.3.2: 2.3.2
  fast-uri@<3.1.5: 3.1.5
  mdast-util-to-hast@<13.2.1: 13.2.1
  ajv@<8.18.0: 8.18.0
  diff@<4.0.4: 4.0.4
