export { createLiveIconLoader } from "./liveLoader.js";
export type { LiveIconLoaderOptions } from "./liveLoader.js";
export { liveIconCollections } from "./liveCollections.js";
export type { LiveIconCollectionConfig } from "./liveCollections.js";
export { iconifyLocalSource } from "./iconify/localSource.js";
export { iconifyApiSource } from "./iconify/apiSource.js";
export { mergeSources } from "./compositeSource.js";
export type { CompositeSource } from "./compositeSource.js";
export { AstroIconError } from "../internal/error.js";
export type { IconSource } from "./source.js";
