export { AstroIconError } from "../internal/error.js";
export { iconify } from "./iconify/loader.js";
export { iconifySource } from "./iconify/source.js";
export { localIcons } from "./local/loader.js";
export { localSource } from "./local/source.js";
export type { LocalSourceOptions } from "./local/source.js";
export { createIconLoader } from "./loader.js";
export type { IconLoaderOptions } from "./loader.js";
export type { IconSource } from "./source.js";
export { parseIconSVG } from "./parseIconSVG.js";
export type { ParseIconSVGOptions } from "./parseIconSVG.js";
export type { IconifySourceOptions, OptimizeFn, IconEntry } from "../../typings/types";
