import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";

interface TypegenState {
  build: Record<string, string[]>;
  live: Record<string, string[]>;
}

// Serializes concurrent writes from multiple loaders running in the same sync.
let chain: Promise<void> = Promise.resolve();

/**
 * Records the full set of icon names available for a collection (not just
 * the ones actually loaded/used - see `iconify.ts`) so its generated types
 * offer autocomplete across everything the pack/source has to offer.
 *
 * Each collection gets its own declaration file under `.astro/astro-icon/`,
 * rather than one file for the whole project - individually easy to find
 * ("which file has mdi's icons?" -> `astro-icon/build-mdi.d.ts`) and only
 * the collections that actually changed get rewritten.
 */
export function recordCollection(
  rootDir: URL,
  kind: "build" | "live",
  collection: string,
  names: string[],
): Promise<void> {
  chain = chain.then(() => writeTypes(rootDir, kind, collection, names));
  return chain;
}

async function writeTypes(
  rootDir: URL,
  kind: "build" | "live",
  collection: string,
  names: string[],
): Promise<void> {
  const astroDir = new URL("./.astro/", rootDir);
  const partialsDir = new URL("./astro-icon/", astroDir);
  const stateFile = new URL("./astro-icon.json", astroDir);
  const indexFile = new URL("./astro-icon.d.ts", astroDir);
  await ensureDir(partialsDir);

  const state = await readState(stateFile);
  state[kind][collection] = names;
  await writeFile(stateFile, JSON.stringify(state));

  await writePartial(partialsDir, kind, collection, names);
  await writeFile(indexFile, renderIndex(state));
}

async function writePartial(
  partialsDir: URL,
  kind: "build" | "live",
  collection: string,
  names: string[],
): Promise<void> {
  const partialFile = new URL(`./${partialFilename(kind, collection)}`, partialsDir);
  const currentHash = namesHash(names);
  const oldHash = await tryGetHash(partialFile);
  if (currentHash === oldHash) return;

  await writeFile(partialFile, renderPartial(kind, collection, names, currentHash));
}

function partialFilename(kind: "build" | "live", collection: string): string {
  // Collection names are arbitrary identifiers chosen by the user in
  // content.config.ts/live.config.ts - sanitize before using one as a
  // filename. Prefixed by kind so a build and a live collection that
  // happen to share a name (different files, different namespaces) don't
  // collide.
  const safeName = collection.replace(/[^a-zA-Z0-9_-]/g, "_");
  return `${kind}-${safeName}.d.ts`;
}

function renderPartial(
  kind: "build" | "live",
  collection: string,
  names: string[],
  hash: string,
): string {
  const key = JSON.stringify(collection);
  const interfaceName = kind === "build" ? "Collections" : "LiveCollections";
  // A build collection with zero names is genuinely empty ("never" - no
  // value is valid). A live collection with zero names just means its
  // source couldn't list its icons (no `listIcons`, or it failed/isn't
  // possible, e.g. an API-only pack with no local install) - any string
  // might still resolve at request time, so it falls back to `string`
  // rather than `never`.
  const valueType =
    names.length > 0 ? unionOf(names) : kind === "build" ? "never" : "string";
  const body = `interface ${interfaceName} {\n\t\t${key}: ${valueType};\n\t}`;

  return `// Automatically generated by astro-icon
// ${hash}

declare namespace AstroIcon {
\t${body}
}
`;
}

function unionOf(names: string[]): string {
  return names.map((icon) => `"${icon}"`).join(" | ");
}

function renderIndex(state: TypegenState): string {
  const references = [
    ...Object.keys(state.build).map((name) => partialFilename("build", name)),
    ...Object.keys(state.live).map((name) => partialFilename("live", name)),
  ]
    .sort()
    .map((file) => `/// <reference path="./astro-icon/${file}" />`)
    .join("\n");

  return `// Automatically generated by astro-icon - references one declaration file
// per collection under ./astro-icon/, each merging into the AstroIcon
// namespace used by IconName/LiveIconName.
${references}
`;
}

async function readState(stateFile: URL): Promise<TypegenState> {
  try {
    const text = await readFile(stateFile, { encoding: "utf-8" });
    const parsed = JSON.parse(text) as Partial<TypegenState>;
    return { build: parsed.build ?? {}, live: parsed.live ?? {} };
  } catch {
    return { build: {}, live: {} };
  }
}

function namesHash(names: string[]): string {
  return createHash("sha256")
    .update([...names].sort().join(","))
    .digest("hex");
}

async function tryGetHash(path: URL): Promise<string | void> {
  try {
    const text = await readFile(path, { encoding: "utf-8" });
    return text.split("\n", 2)[1]?.replace("// ", "");
  } catch {}
}

async function ensureDir(path: URL): Promise<void> {
  try {
    await mkdir(path, { recursive: true });
  } catch {}
}
