import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";

type TypegenKind = "build" | "live" | "packs";

interface TypegenState {
  build: Record<string, string[]>;
  live: Record<string, string[]>;
  packs: Record<string, string[]>;
}

// An empty build collection types as `never`; an empty live collection or pack falls back to `string`, since it may just mean the source couldn't list its icons.
const KIND_CONFIG = {
  build: { interfaceName: "Collections", emptyValueType: "never" },
  live: { interfaceName: "LiveCollections", emptyValueType: "string" },
  packs: { interfaceName: "Packs", emptyValueType: "string" },
} as const satisfies Record<TypegenKind, { interfaceName: string; emptyValueType: string }>;

// Serializes concurrent writes from multiple loaders running in the same sync.
let chain: Promise<void> = Promise.resolve();

/** Records a collection's full icon name set to its own declaration file under `.astro/astro-icon/`, for autocomplete. */
export function recordCollection(
  rootDir: URL,
  kind: TypegenKind,
  collection: string,
  names: string[],
): Promise<void> {
  chain = chain.then(() => writeTypes(rootDir, kind, collection, names));
  return chain;
}

/** Records an Iconify pack's full, unfiltered icon name set, so `icons: [...]` options can be typed and autocompleted against it. */
export function recordPack(rootDir: URL, pack: string, names: string[]): Promise<void> {
  return recordCollection(rootDir, "packs", pack, names);
}

async function writeTypes(
  rootDir: URL,
  kind: TypegenKind,
  collection: string,
  names: string[],
): Promise<void> {
  const astroDir = new URL("./.astro/", rootDir);
  const partialsDir = new URL("./astro-icon/", astroDir);
  const stateFile = new URL("./astro-icon.json", astroDir);
  const indexFile = new URL("./astro-icon.d.ts", astroDir);
  await ensureDir(partialsDir);

  const state = await readState(stateFile);
  state[kind][collection] = names;
  await writeFile(stateFile, JSON.stringify(state));

  await writePartial(partialsDir, kind, collection, names);
  await writeFile(indexFile, renderIndex(state));
}

async function writePartial(
  partialsDir: URL,
  kind: TypegenKind,
  collection: string,
  names: string[],
): Promise<void> {
  const partialFile = new URL(`./${partialFilename(kind, collection)}`, partialsDir);
  const currentHash = namesHash(names);
  const oldHash = await tryGetHash(partialFile);
  if (currentHash === oldHash) return;

  await writeFile(partialFile, renderPartial(kind, collection, names, currentHash));
}

function partialFilename(kind: TypegenKind, collection: string): string {
  // Sanitized since collection names are arbitrary user-chosen identifiers; prefixed by kind to avoid a name collision across kinds.
  const safeName = collection.replace(/[^a-zA-Z0-9_-]/g, "_");
  return `${kind}-${safeName}.d.ts`;
}

function renderPartial(
  kind: TypegenKind,
  collection: string,
  names: string[],
  hash: string,
): string {
  const key = JSON.stringify(collection);
  const { interfaceName, emptyValueType } = KIND_CONFIG[kind];
  const valueType = names.length > 0 ? unionOf(names) : emptyValueType;
  const body = `interface ${interfaceName} {\n\t\t${key}: ${valueType};\n\t}`;

  return `// Automatically generated by astro-icon
// ${hash}

declare namespace AstroIcon {
\t${body}
}
`;
}

function unionOf(names: string[]): string {
  return names.map((icon) => `"${icon}"`).join(" | ");
}

function renderIndex(state: TypegenState): string {
  const references = [
    ...Object.keys(state.build).map((name) => partialFilename("build", name)),
    ...Object.keys(state.live).map((name) => partialFilename("live", name)),
    ...Object.keys(state.packs).map((name) => partialFilename("packs", name)),
  ]
    .sort()
    .map((file) => `/// <reference path="./astro-icon/${file}" />`)
    .join("\n");

  return `// Automatically generated by astro-icon - references one declaration file
// per collection under ./astro-icon/, each merging into the AstroIcon
// namespace used by IconName/LiveIconName.
${references}
`;
}

async function readState(stateFile: URL): Promise<TypegenState> {
  try {
    const text = await readFile(stateFile, { encoding: "utf-8" });
    const parsed = JSON.parse(text) as Partial<TypegenState>;
    return { build: parsed.build ?? {}, live: parsed.live ?? {}, packs: parsed.packs ?? {} };
  } catch {
    return { build: {}, live: {}, packs: {} };
  }
}

function namesHash(names: string[]): string {
  return createHash("sha256")
    .update([...names].sort().join(","))
    .digest("hex");
}

async function tryGetHash(path: URL): Promise<string | undefined> {
  try {
    const text = await readFile(path, { encoding: "utf-8" });
    return text.split("\n", 2)[1]?.replace("// ", "");
  } catch {}
}

async function ensureDir(path: URL): Promise<void> {
  try {
    await mkdir(path, { recursive: true });
  } catch {}
}
